device: 'cpu'
# device: 'cuda: 0'

n_rounds: 1
epochs: 1
n_clients: 10
fraction: 0.8
batch_size: 16
lr: 0.9

seed: 2022

root: ${env:PWD}
savedir: ${env:PWD}/../output/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${env:PWD}/../output/${now:%Y-%m-%d_%H-%M-%S}
