defaults:
  - fed_torch: decentralized

dataset_download_path: ${hydra:runtime.cwd}/../data/
dataset: cifar10
device: 'cpu'

seed: 2022
root: ${hydra:runtime.cwd}
savedir: ${hydra:runtime.cwd}/../output/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/../output/${now:%Y-%m-%d_%H-%M-%S}
