device: 'cpu'
# device: 'cuda'
dataset: cifar10
dataset_download_path: ${hydra:runtime.cwd}/../datasets/data/
divergence: 0
n_rounds: 1
epochs: 50 # increase this
n_clients: 3 # increase this
fraction: 0.8
batch_size: 16
lr: 0.001

seed: 2022
root: ${hydra:runtime.cwd}
savedir: ${hydra:runtime.cwd}/../output/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/../output/${now:%Y-%m-%d_%H-%M-%S}
