device: 'cpu'
# device: 'cuda: 0'
dataset: cifar10
dataset_download_path: ../../datasets/data/
divergence: 0
n_rounds: 1
epochs: 1
n_clients: 5
fraction: 0.8
batch_size: 16
lr: 0.9

seed: 2022
root: ${hydra:runtime.cwd}
savedir: ${hydra:runtime.cwd}/../output/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/../output/${now:%Y-%m-%d_%H-%M-%S}
